### Site Settings ###
title               : Younga Shin
tagline             : Younga Shin's personal website.
description         : >-
                      A 24-year-old Master student from South Korea, passionate about Deep Learning in Civil and Environmental Engineering.
baseurl             : "/"                            # Comment if you are hosting your site at <your-username>.github.io directly
url                 : https://www.youngahshin.com
repository          : shinyounga/shinyounga.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                             # Opens external URLs in new tab (works for posts, projects, navbar and footer only)
source              : .
layouts_dir         : _layouts
includes_dir        : _includes
sass:
  sass_dir: ./_sass
logo                : assets/big-logo.png


### Plugins ###
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/about.md
  - pages/thanks.md
  - pages/failed.md
  - pages/privacy.md
  - pages/cookies.md


### Author Info ###
author:
  name              : Younga Shin
  picture           : assets/profile.jpg
  url               : https://youngashin.com
#  behance           : your_username
# dribbble          : your_username
  email             : /contact
#  facebook          : your_username
  github            : shinyounga
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : Younga Shin
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username

### Social SEO###
social:
  name: Younga Shin
  links:
    - https://www.linkedin.com/in/younga-shin/
    - https://scholar.google.com/citations?user=PS_CX0AAAAA
    - http://orcid.org/0009-0006-6792-6395
    - https://github.com/shinyounga

### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics


### Buy me a coffee ###
# See https://www.ko-fi.com/
ko-fi:
  enabled: false
  username: alesordo
  color: '#dc3545'
  text: An espresso?                                   # Text on the button


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable Remark42 comments
  - scope:
      path:            "assets"
    values:
      sitemap:         false


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
